ALTER TYPE "Role"
RENAME VALUE 'COLLABORATEUR'
TO 'COLLABORATEUR_ASSOCIE';

ALTER TYPE "Role"
ADD VALUE IF NOT EXISTS 'AVOCAT_STAGIAIRE';

ALTER TYPE "Role"
ADD VALUE IF NOT EXISTS 'JURISTE';

ALTER TYPE "Role"
ADD VALUE IF NOT EXISTS 'ARCHIVISTE';

ALTER TABLE "User"
ALTER COLUMN "role"
SET DEFAULT 'COLLABORATEUR_ASSOCIE';